#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 03 15:34:11 BRT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=4
shaderPack=MakeUp UF             [Otimizado] \u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7r FPS.zip
enableShaders=true
