#This is a Jekyll file to exclude directories to not be uploaded and be live in GitHub Pages of this Repository

#exclude: 
#  - "Minecraft-Plus-Compiled"
#  - "Minecraft-Plus-Source"
#  - "This-Repository"