#The exaustion applied to the Player that was used the Dash. (Type of INT. Range of 0~128.)
#Range: 0 ~ 128
dashExaustion = 16
#The range where the Player can reach Entities. (Type of INT. Range of 3~64.)
#Range: 3 ~ 64
dashRange = 48
#Items ID, that can use the Dash of this Gap Closer System. (Type of STRING_ARRAY. For each STRING item, use this format: "minecraft:diamond_sword".)
itemsWithDashSkill = ["spartanweaponry:wooden_glaive", "spartanweaponry:stone_glaive", "spartanweaponry:iron_glaive", "spartanweaponry:golden_glaive", "spartanweaponry:diamond_glaive", "spartanweaponry:netherite_glaive"]
#If enabled, Dash will only work if the other hand (the one not holding the allowed item) is empty. (Type of BOOL. true/false.)
requiresOtherHandEmpty = false
#The cooldown, in seconds, to be applied to the allowed item, on Dash use. (Type of FLOAT. Range of 1.5~60.0)
#Range: 1.5 ~ 60.0
dashCooldownSecs = 3.5
#The level of the Absorption to apply on Player when Dash comes to Target. Each level grants 4 of HP. (Type of INT. Range of 0~9.)
#Range: 0 ~ 9
dashEndAbsorptionLevel = 1
#The duration, in seconds, of the Absorption applied to the Player. (Type of INT. Range of 0~15.)
#Range: 0 ~ 15
dashEndAbsorptionDurationSecs = 5
#The Attack Speed buff, in percent, to apply to the Player while the Combo effect persists. (Type of INT. Range of 0~100.)
#Range: 0 ~ 100
dashEndComboAttackSpeedBuff = 90
#The Life Steal buff, in percent, to apply to the Player while the Combo effect persists. (Type of INT. Range of 0~100.)
#Range: 0 ~ 100
dashEndComboLifeStealBuff = 10
#The duration, in seconds, of Combo applied for Player. Combo grants buffs to the Player, but if the Player changes to disallowed item on Main Hand, he receives debuffs while the Combo persists. (Type of INT. Range of 0~15.)
#Range: 0 ~ 15
dashEndComboDurationSecs = 5
#If enabled, the Shields of the Player that was started Dash will be disbled while the Combo effect persists, after the Player reaches the target of Dash. (Type of BOOL. true/false.)
dashEndDisableShields = true
#The Stun duration, that will be applied to the Target Mob of the Dash. (Type of FLOAT. Range of 1.0~8.0)
#Range: 1.0 ~ 8.0
targetMobStunDurationSecs = 2.3
#The radius, in blocks, of Slow apply on near Mobs when the Dash reach the Target Mob. (Type of INT. Range of 1~10.)
#Range: 1 ~ 10
targetMobAffectAreaRadius = 5
#The Slow duration, that will be applied to the Mobs near of the Target Mob of the Dash. (Type of FLOAT. Range of 1.0~15.0)
#Range: 1.0 ~ 15.0
targetMobSlowDurationSecs = 5.0
#The level of the Slow to apply on Target Player when Dash finishes. Each level grants 15% of Movement Slow. (Type of INT. Range of 0~5.)
#Range: 0 ~ 5
targetPlayerSlowLevel = 1
#The Slow duration, in seconds, that will be applied to the Target Player of the Dash. (Type of INT. Range of 0~15.)
#Range: 0 ~ 15
targetPlayerSlowDurationSecs = 5
#The level of the Poison to apply on Target Player when Dash finishes. Level 1 gives damage each 25 ticks. Level 2 gives damage each 12 ticks. (Type of INT. Range of 0~1.)
#Range: 0 ~ 1
targetPlayerPoisonLevel = 0
#The Poison duration, in seconds, that will be applied to the Target Player of the Dash. (Type of INT. Range of 0~15.)
#Range: 0 ~ 15
targetPlayerPoisonDurationSecs = 5

