items {
    "extrashields:diamond_shield"=1024
    "extrashields:golden_shield"=256
    "extrashields:iron_shield"=512
    "extrashields:netherite_shield"=2048
    "extrashields:wooden_shield"=128
    "minecraft:netherite_axe"=2500
    "minecraft:netherite_boots"=680
    "minecraft:netherite_chestplate"=720
    "minecraft:netherite_helmet"=650
    "minecraft:netherite_hoe"=2500
    "minecraft:netherite_leggings"=700
    "minecraft:netherite_pickaxe"=2500
    "minecraft:netherite_shovel"=2500
    "minecraft:netherite_sword"=2500
    "minecraft:shield"=256
    "stardew_fishing:cork_bobber"=128
    "stardew_fishing:quality_bobber"=128
    "stardew_fishing:sonar_bobber"=512
    "stardew_fishing:trap_bobber"=256
    "stardew_fishing:treasure_bobber"=128
}
