#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 03 04:49:51 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=4
shaderPack=6. MakeUp UF          [Otimizado] \u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7r FPS.zip
enableShaders=false
