#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Oct 03 18:53:56 BRT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=4
shaderPack=Complementary     [Equilibrado] \u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A7f\u2605\u00A78\u2605\u00A78\u2605\u00A78\u2605\u00A78\u2605\u00A7r FPS.zip
enableShaders=false
