#Raw Milk Bucket stack size limit
#Range: 1 ~ 64
stackLimitRawMilk = 1
#Pasteurized Milk Bucket stack size limit
#Range: 1 ~ 64
stackLimitPasteurizedMilk = 16
#Chocolate Milk Bucket stack size limit
#Range: 1 ~ 64
stackLimitChocolateMilk = 1
#Raw Milk status duration
#Range: > 0
durationRawMilk = 600
#Chocolate Milk status duration
#Range: > 0
durationChocolateMilk = 600

